### ISSUE TITLE
Broken download links

### ISSUE THREAD

**Issue by corndog2000** [Anass-23/5G-Network#1]
These two links in the readme are broken. They go to error 404 pages and won't download with wget.

[https://gitlab.eurecom.fr/oai/openairinterface5g/-/raw/develop/doc/tutorial_resources/docker-compose-basic-nrf.yaml?inline=false](https://gitlab.eurecom.fr/oai/openairinterface5g/-/raw/develop/doc/tutorial_resources/docker-compose-basic-nrf.yaml?inline=false)

[https://gitlab.eurecom.fr/oai/openairinterface5g/-/raw/develop/doc/tutorial_resources/oai_db.sql?inline=false](https://gitlab.eurecom.fr/oai/openairinterface5g/-/raw/develop/doc/tutorial_resources/oai_db.sql?inline=false)

**Comment by corndog2000** [comment]
See my pull request to fix the broken links: [https://github.com/Anass-23/5G-Network/pull/2](https://github.com/Anass-23/5G-Network/pull/2)

**Comment by Anass-23** [comment]
I've seen that OAI has changed some links and tutorials, thanks for the fix!
