### ISSUE TITLE
Configuration file not accurate

### ISSUE THREAD

**Issue by corndog2000** [Anass-23/5G-Network#4]
The file `docker-compose-basic-nfr.yaml` does not have the listed MCC and MNC config options. From this section: [https://github.com/Anass-23/5G-Network#configuration](https://github.com/Anass-23/5G-Network#configuration)

**Comment by Anass-23** [comment]
Correct me if I'm wrong, maybe im not understanding where is the issue. 
The MCC and MNC configuration options can differ from the ones of this project depending on the programmed SIM card, in our case we've received the SIM cards from OAI already programmed with the corresponding info:

> [Change MCC and MNC values according to the programmed SIM card]. In our case, <MCC_SIM> and <MNC_SIM> are 208 and 92, respectively.

**Comment by corndog2000** [comment]
I thought the MCC and MNC settings were going to match the information you programmed into the SIM card with this command.

`sudo ./program_uicc --adm 12345678 --imsi 001010000000001 --isdn 00000001 --acc 0001 --key fec86ba6eb707ed08905757b1bb44b8f --opc C42449363BBAD02B66D16BC975D77CC1 --spn "OpenAirInterface" --authenticate`

If someone is following this guide and uses this command on a blank SIM card they should change the config files so the MCC is 001 and the MNC is 01 correct?

**Comment by Anass-23** [comment]
Ahhh okay! Now I understand, yes you are correct, if the SIM card is programmed with the command:

```bash
sudo ./program_uicc --adm 12345678 --imsi 001010000000001 --isdn 00000001 --acc 0001 --key fec86ba6eb707ed08905757b1bb44b8f --opc C42449363BBAD02B66D16BC975D77CC1 --spn "OpenAirInterface" --authenticate
```

 then the MCC and MNC should be 001 and 01 accordingly.
