### ISSUE TITLE
Starting the CN5G docker error

### ISSUE THREAD

**Issue by corndog2000** [Anass-23/5G-Network#5]
I am getting this error when trying to run oai-cn5g.

`Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/home/jschroedl/oai-cn5g-fed/docker-compose/conf/config.yaml" to rootfs at "/openair-nrf/etc/config.yaml": mount /home/jschroedl/oai-cn5g-fed/docker-compose/conf/config.yaml:/openair-nrf/etc/config.yaml (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
 Incorrect/Unsupported executing command docker-compose -f docker-compose-basic-nrf.yaml up -d`

Somewhere in the setup a file is not copied to the correct location.

**Comment by Anass-23** [comment]
Hi there!
Sorry for the late response, this error may represent that the `config.yaml` file is not located at the corresponding directory.
Are you sure that you have the `config.yaml` at `/home/jschroedl/oai-cn5g-fed/docker-compose/conf/`?

Also:
- Check that you have the corresponding directories and also permissions needed for running `docker-compose`
- Review also `docker-compose-basic-nrf.yaml`

I've seen that OAI have been changing stuff in the repository (links, manuals) I don't know if they've also modified some configuration files.
