### ISSUE TITLE
openairinterface5g build error

### ISSUE THREAD

**Issue by corndog2000** [Anass-23/5G-Network#6]
When trying to run the second build command for OAI5G I am getting an error that is preventing the build from continuing.

Command: ```./build\_oai -w USRP --ninja --nrUE --gNB --build-lib all -c```

Error:
```
CMake Error at CMakeLists.txt:506 (message):
  could not find poll-mode driver for AccelerComm T2 LDPC Offload
  (rte_baseband_accl_ldpc.so)
```

**Comment by mackskaren** [comment]
this may be a bit late, but this problem stems from the `--build-lib all` argument. When you do this, it has it build with all optional libraries that aren't needed. the two that I ran into were the `ldpc_cuda and ldpc_t2` libraries, which adds support for nvidia gpus and some amd accelerator card, both of which you probably don't need initially. from the `openairinterface5g/doc/BUILD.md` file, it says 
'There are a number of optional libraries that can be built in support of the
RAN, such as telnetsrv, scopes, offloading libraries, etc.
Using the help option of the build script you can get the list of available optional libraries.

./build_oai --build-lib all # build all
./build_oai --build-lib telnetsrv  # build only telnetsrv
./build_oai --build-lib "telnetsrv enbscope uescope nrscope nrqtscope"
./build_oai --build-lib telnetsrv --build-lib nrqtscope

The following libraries are build in CI and should always work: telnetsrv,
enbscope, uescope, nrscope, nrqtscope.

Some libraries have further dependencies and might not build on every system:
enbscope, uescope, nrscope: libforms/X
nrqtscope: Qt5
ldpc_cuda: CUDA
websrv: npm and others
ldpc_t2: DPDK with patch'

build with the libraries you want I guess, which is `--build-lib "<list of libraries in quotes>"`, or just omit the `--build-lib` argument entirely, as it is not necessary. I did it without cuda and t2 and it solved that problem. you may need to install some other dependencies if you choose to build with optional libraries, though you should be able to just `apt install` them.
